name: build-dist

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build distributable
        uses: docker/build-push-action@v2.7.0
        with:
          file: Dockerfile
          outputs: dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: osxcross-build.tar.zst
          path: dist/*
